### ISSUE TITLE
How do I make a new theme?

### ISSUE THREAD

**Issue by tyeeman** [Kylob/BootPress#1]
I would like to take a random bootstrap template and convert it for use with Bootpress. Any tips you can shed. I am not a coder but copy/paste can do wonders.

I suppose a generic html/css template from the web is not compatible with Bootpress??

**Comment by Kylob** [comment]
Any and all html/css/js is compatible with BootPress.  Have you downloaded the files and signed into your /admin page?  There is a template there that you can work from.  It is mdo's Bootstrap blog theme that I pretty much just copied and pasted.  Checkout the [BootPress Themes Documentation](https://www.bootpress.org/docs/themes/) for more tips.

**Comment by tyeeman** [comment]
Yes, I see that theme and I have selected to edit it just to see what the UI does. It shows the exact code shown in the BootPress link you gave me above. I can't find the link to mdo's theme so I can compare it to what is in the BootPress theme. Do you have the link to his theme handy?

Update - I found a link to mdo's demo page blog layout. Looks like I really have to be into working with coding to be able to create a BootPress theme from html code. Hmm....I was expecting to add BootPress tags to the original html and create a theme that way. Can this be done?

**Comment by Kylob** [comment]
Well, there are no BootPress tags per say, unless you mean Smarty variables, but in themes that amounts to `{$content}`.  You are correct however, it is all just html and css.
